### ISSUE TITLE
fail to send crash

### ISSUE THREAD

**Issue by Paul75** [mahdit83/advancedSmsManager#4]
Hello,

When I do this :
```
final Context ctx = this.context;

        new Thread(new Runnable() {
            @Override
            public void run() {

                SmsHandler.builder(context, address)
                        .needToShowDialog(false)
                        .build().sendSms("GOMPOST", message, new MySmsManager.SMSManagerCallBack() {
                    @Override
                    public void afterSuccessfulSMS(int smsId) {
                        Toast.makeText(ctx, "Le message a bien été envoyé", Toast.LENGTH_LONG).show();
                    }

                    @Override
                    public void afterDelivered(int smsId) {

                    }

                    @Override
                    public void afterUnSuccessfulSMS(int smsId, String message) {
                        Toasty.error(ctx, "ERREUR : Le message n'a pas pu être envoyé", Toast.LENGTH_LONG, true).show();
                    }

                    @Override
                    public void onCarrierNameNotMatch(int smsId, String message) {
                        Toasty.error(ctx, "ERREUR : Le message n'a pas pu être envoyé : le numéro est invalide", Toast.LENGTH_LONG, true).show();
                    }
                });
            }
        }).start();
```

The application crash but send SMS :
```
Device: Asus ASUS_Z012D

Stack trace:
java.lang.RuntimeException: Error receiving broadcast Intent { act=SMS_SENT flg=0x10 (has extras) } in ir.mtajik.android.advancedsmsmanager.model.MySmsManager$1@c5a000f
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1137)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6097)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ProgressBar.setVisibility(int)' on a null object reference
        at ir.mtajik.android.advancedsmsmanager.view.SendSmsViewImpl.endView(SendSmsViewImpl.java:102)
        at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl$1.afterSuccessfulSMS(SendSmsPresenterImpl.java:156)
        at ir.mtajik.android.advancedsmsmanager.model.MySmsManager$1.onReceive(MySmsManager.java:86)
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1126)
        ... 7 more
```

Why ?

**Comment by Paul75** [comment]
The same error if I clone your repo and launch program ....

**Comment by mahdit83** [comment]
@Paul75  It seems you did not passed progressBar with id "progressBar_total" as i mentioned in help. So inset visibility it can not be casted and null pointer exception raised.

**Comment by mahdit83** [comment]
@Paul75 If you once click on sync project with gradle errors will gone. check this out: https://stackoverflow.com/a/47494256/1498586

**Comment by Paul75** [comment]
Hello,

Thanks but I don't want send sms with dialog .....

Why I must have progress bar ? not works without?

Thanks

**Comment by mahdit83** [comment]
You was right i find a bug and it will be fix soon. thanks.

**Comment by mahdit83** [comment]
@Paul75 It is fixed, also updated Maven repo to 'ir.mtajik.android:advancedsmsmanager:1.0.6'

**Comment by Paul75** [comment]
Helo,

Now not works !!!! Now not send SMS ...

got in console : 
```
01-29 23:30:18.629 7002-7002/fr.laposte.gompost E/ActivityThread: Activity fr.laposte.gompost.activity.ControlsActivity has leaked IntentReceiver ir.mtajik.android.advancedsmsmanager.model.MySmsManager$2@1b4a84 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                  android.app.IntentReceiverLeaked: Activity fr.laposte.gompost.activity.ControlsActivity has leaked IntentReceiver ir.mtajik.android.advancedsmsmanager.model.MySmsManager$2@1b4a84 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                      at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1174)
                                                                      at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:947)
                                                                      at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1342)
                                                                      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1322)
                                                                      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1316)
                                                                      at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:593)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.MySmsManager.sendSMS(MySmsManager.java:138)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.MySmsManager.generateSMS(MySmsManager.java:55)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.SendSmsModelImpl.generateSMSForMultiSimCards(SendSmsModelImpl.java:19)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.sendSmsForNewPhones(SendSmsPresenterImpl.java:149)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.sendSmsFromSubscriptionIdIndex(SendSmsPresenterImpl.java:110)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.prepareSendSms(SendSmsPresenterImpl.java:95)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.startWiringUp(SendSmsPresenterImpl.java:66)
                                                                      at ir.mtajik.android.advancedsmsmanager.SmsHandler.sendSms(SmsHandler.java:65)
                                                                      at fr.laposte.gompost.utils.MessagesManager$3.run(MessagesManager.java:103)
                                                                      at java.lang.Thread.run(Thread.java:761)
01-29 23:30:18.630 7002-7002/fr.laposte.gompost E/ActivityThread: Activity fr.laposte.gompost.activity.ControlsActivity has leaked IntentReceiver ir.mtajik.android.advancedsmsmanager.model.MySmsManager$2@26b226d that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                  android.app.IntentReceiverLeaked: Activity fr.laposte.gompost.activity.ControlsActivity has leaked IntentReceiver ir.mtajik.android.advancedsmsmanager.model.MySmsManager$2@26b226d that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                      at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1174)
                                                                      at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:947)
                                                                      at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1342)
                                                                      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1322)
                                                                      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1316)
                                                                      at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:593)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.MySmsManager.sendSMS(MySmsManager.java:138)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.MySmsManager.generateSMS(MySmsManager.java:55)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.SendSmsModelImpl.generateSMSForMultiSimCards(SendSmsModelImpl.java:19)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.sendSmsForNewPhones(SendSmsPresenterImpl.java:149)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.sendSmsFromSubscriptionIdIndex(SendSmsPresenterImpl.java:110)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.prepareSendSms(SendSmsPresenterImpl.java:95)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.startWiringUp(SendSmsPresenterImpl.java:66)
                                                                      at ir.mtajik.android.advancedsmsmanager.SmsHandler.sendSms(SmsHandler.java:65)
                                                                      at fr.laposte.gompost.utils.MessagesManager$3.run(MessagesManager.java:103)
                                                                      at java.lang.Thread.run(Thread.java:761)
01-29 23:30:18.632 7002-7002/fr.laposte.gompost E/ActivityThread: Activity fr.laposte.gompost.activity.ControlsActivity has leaked IntentReceiver ir.mtajik.android.advancedsmsmanager.model.MySmsManager$2@311ad45 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                  android.app.IntentReceiverLeaked: Activity fr.laposte.gompost.activity.ControlsActivity has leaked IntentReceiver ir.mtajik.android.advancedsmsmanager.model.MySmsManager$2@311ad45 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                      at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1174)
                                                                      at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:947)
                                                                      at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1342)
                                                                      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1322)
                                                                      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1316)
                                                                      at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:593)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.MySmsManager.sendSMS(MySmsManager.java:138)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.MySmsManager.generateSMS(MySmsManager.java:55)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.SendSmsModelImpl.generateSMSForMultiSimCards(SendSmsModelImpl.java:19)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.sendSmsForNewPhones(SendSmsPresenterImpl.java:149)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.sendSmsFromSubscriptionIdIndex(SendSmsPresenterImpl.java:110)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.prepareSendSms(SendSmsPresenterImpl.java:95)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.startWiringUp(SendSmsPresenterImpl.java:66)
                                                                      at ir.mtajik.android.advancedsmsmanager.SmsHandler.sendSms(SmsHandler.java:65)
                                                                      at fr.laposte.gompost.utils.MessagesManager$3.run(MessagesManager.java:103)
                                                                      at java.lang.Thread.run(Thread.java:761)
01-29 23:30:18.634 7002-7002/fr.laposte.gompost E/ActivityThread: Activity fr.laposte.gompost.activity.ControlsActivity has leaked IntentReceiver ir.mtajik.android.advancedsmsmanager.model.MySmsManager$1@3fb78d8 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                  android.app.IntentReceiverLeaked: Activity fr.laposte.gompost.activity.ControlsActivity has leaked IntentReceiver ir.mtajik.android.advancedsmsmanager.model.MySmsManager$1@3fb78d8 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                      at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1174)
                                                                      at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:947)
                                                                      at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1342)
                                                                      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1322)
                                                                      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1316)
                                                                      at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:593)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.MySmsManager.sendSMS(MySmsManager.java:117)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.MySmsManager.generateSMS(MySmsManager.java:55)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.SendSmsModelImpl.generateSMSForMultiSimCards(SendSmsModelImpl.java:19)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.sendSmsForNewPhones(SendSmsPresenterImpl.java:149)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.sendSmsFromSubscriptionIdIndex(SendSmsPresenterImpl.java:110)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.prepareSendSms(SendSmsPresenterImpl.java:95)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.startWiringUp(SendSmsPresenterImpl.java:66)
                                                                      at ir.mtajik.android.advancedsmsmanager.SmsHandler.sendSms(SmsHandler.java:65)
                                                                      at fr.laposte.gompost.utils.MessagesManager$3.run(MessagesManager.java:103)
                                                                      at java.lang.Thread.run(Thread.java:761)
01-29 23:30:18.637 7002-7002/fr.laposte.gompost E/ActivityThread: Activity fr.laposte.gompost.activity.ControlsActivity has leaked IntentReceiver ir.mtajik.android.advancedsmsmanager.model.MySmsManager$1@5629716 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                  android.app.IntentReceiverLeaked: Activity fr.laposte.gompost.activity.ControlsActivity has leaked IntentReceiver ir.mtajik.android.advancedsmsmanager.model.MySmsManager$1@5629716 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                      at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1174)
                                                                      at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:947)
                                                                      at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1342)
                                                                      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1322)
                                                                      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1316)
                                                                      at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:593)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.MySmsManager.sendSMS(MySmsManager.java:117)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.MySmsManager.generateSMS(MySmsManager.java:55)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.SendSmsModelImpl.generateSMSForMultiSimCards(SendSmsModelImpl.java:19)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.sendSmsForNewPhones(SendSmsPresenterImpl.java:149)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.sendSmsFromSubscriptionIdIndex(SendSmsPresenterImpl.java:110)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.prepareSendSms(SendSmsPresenterImpl.java:95)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.startWiringUp(SendSmsPresenterImpl.java:66)
                                                                      at ir.mtajik.android.advancedsmsmanager.SmsHandler.sendSms(SmsHandler.java:65)
                                                                      at fr.laposte.gompost.utils.MessagesManager$3.run(MessagesManager.java:103)
                                                                      at java.lang.Thread.run(Thread.java:761)
01-29 23:30:18.638 7002-7002/fr.laposte.gompost E/ActivityThread: Activity fr.laposte.gompost.activity.ControlsActivity has leaked IntentReceiver ir.mtajik.android.advancedsmsmanager.model.MySmsManager$1@6073897 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                  android.app.IntentReceiverLeaked: Activity fr.laposte.gompost.activity.ControlsActivity has leaked IntentReceiver ir.mtajik.android.advancedsmsmanager.model.MySmsManager$1@6073897 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                      at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1174)
                                                                      at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:947)
                                                                      at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1342)
                                                                      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1322)
                                                                      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1316)
                                                                      at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:593)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.MySmsManager.sendSMS(MySmsManager.java:117)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.MySmsManager.generateSMS(MySmsManager.java:55)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.SendSmsModelImpl.generateSMSForMultiSimCards(SendSmsModelImpl.java:19)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.sendSmsForNewPhones(SendSmsPresenterImpl.java:149)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.sendSmsFromSubscriptionIdIndex(SendSmsPresenterImpl.java:110)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.prepareSendSms(SendSmsPresenterImpl.java:95)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.startWiringUp(SendSmsPresenterImpl.java:66)
                                                                      at ir.mtajik.android.advancedsmsmanager.SmsHandler.sendSms(SmsHandler.java:65)
                                                                      at fr.laposte.gompost.utils.MessagesManager$3.run(MessagesManager.java:103)
                                                                      at java.lang.Thread.run(Thread.java:761)
01-29 23:30:18.641 7002-7002/fr.laposte.gompost E/ActivityThread: Activity fr.laposte.gompost.activity.ControlsActivity has leaked IntentReceiver ir.mtajik.android.advancedsmsmanager.model.MySmsManager$1@95c59bc that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                  android.app.IntentReceiverLeaked: Activity fr.laposte.gompost.activity.ControlsActivity has leaked IntentReceiver ir.mtajik.android.advancedsmsmanager.model.MySmsManager$1@95c59bc that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                      at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1174)
                                                                      at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:947)
                                                                      at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1342)
                                                                      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1322)
                                                                      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1316)
                                                                      at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:593)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.MySmsManager.sendSMS(MySmsManager.java:117)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.MySmsManager.generateSMS(MySmsManager.java:55)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.SendSmsModelImpl.generateSMSForMultiSimCards(SendSmsModelImpl.java:19)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.sendSmsForNewPhones(SendSmsPresenterImpl.java:149)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.sendSmsFromSubscriptionIdIndex(SendSmsPresenterImpl.java:110)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.prepareSendSms(SendSmsPresenterImpl.java:95)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.startWiringUp(SendSmsPresenterImpl.java:66)
                                                                      at ir.mtajik.android.advancedsmsmanager.SmsHandler.sendSms(SmsHandler.java:65)
                                                                      at fr.laposte.gompost.utils.MessagesManager$3.run(MessagesManager.java:103)
                                                                      at java.lang.Thread.run(Thread.java:761)
01-29 23:30:18.642 7002-7002/fr.laposte.gompost E/ActivityThread: Activity fr.laposte.gompost.activity.ControlsActivity has leaked IntentReceiver ir.mtajik.android.advancedsmsmanager.model.MySmsManager$2@ff47431 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                  android.app.IntentReceiverLeaked: Activity fr.laposte.gompost.activity.ControlsActivity has leaked IntentReceiver ir.mtajik.android.advancedsmsmanager.model.MySmsManager$2@ff47431 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                      at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1174)
                                                                      at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:947)
                                                                      at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1342)
                                                                      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1322)
                                                                      at android.app.ContextImpl.registerReceiver(ContextImpl.java:1316)
                                                                      at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:593)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.MySmsManager.sendSMS(MySmsManager.java:138)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.MySmsManager.generateSMS(MySmsManager.java:55)
                                                                      at ir.mtajik.android.advancedsmsmanager.model.SendSmsModelImpl.generateSMSForMultiSimCards(SendSmsModelImpl.java:19)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.sendSmsForNewPhones(SendSmsPresenterImpl.java:149)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.sendSmsFromSubscriptionIdIndex(SendSmsPresenterImpl.java:110)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.prepareSendSms(SendSmsPresenterImpl.java:95)
                                                                      at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.startWiringUp(SendSmsPresenterImpl.java:66)
                                                                      at ir.mtajik.android.advancedsmsmanager.SmsHandler.sendSms(SmsHandler.java:65)
                                                                      at fr.laposte.gompost.utils.MessagesManager$3.run(MessagesManager.java:103)
                                                                      at java.lang.Thread.run(Thread.java:761)

```

**Comment by mahdit83** [comment]
@Paul75 why do you run method on another thread? did you test on main thread? (main activity)

**Comment by Paul75** [comment]
because it to send in background .... multiple SMS same time ...

**Comment by mahdit83** [comment]
@Paul75 It will be done in background and no needs for another thread and your method is not gonna work. SmsManager implementation is SmsManager smsManager = SmsManager.getDefault(); so it is single-tone and have its own message pool. So you just need to call sendTextMessage() in pure class in a loop or in my lib: call method in a loop and change SMS_NUMBER in every loop. 

        for (int i = 0; i < userList.size(); i++) {
            SmsHandler.builder(MainActivity.this, userList.get(i).getPhoneNumber())
                    .withCarrierNameFilter("MCI")
                    .withCustomDialogForSendSms(R.layout.my_sms_dialog)
                    .withCustomDialogForChoseSim(R.layout.simcard_choosing_dialog)
                    .needToShowDialog(false)
                    .build().sendSms(DIALOG_MESSAGE, SMS_BODY, this);
        }
       
Note that I implemented callback in activity.
Also I can add SMS_NUMBER in sendSms() method in future.
