### ISSUE TITLE
Null point error

### ISSUE THREAD

**Issue by ravdeepsingh22** [mahdit83/advancedSmsManager#5]
2 13:25:06.247 31577-31577/com.androstock.smsapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.androstock.smsapp, PID: 31577
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
        at android.widget.Toast.<init>(Toast.java:103)
        at android.widget.Toast.makeText(Toast.java:256)
        at ir.mtajik.android.advancedsmsmanager.view.SendSmsViewImpl.showMessage(SendSmsViewImpl.java:116)
        at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.prepareSendSms(SendSmsPresenterImpl.java:111)
        at ir.mtajik.android.advancedsmsmanager.presenter.SendSmsPresenterImpl.startWiringUp(SendSmsPresenterImpl.java:67)
        at ir.mtajik.android.advancedsmsmanager.SmsHandler.sendSms(SmsHandler.java:79)
        at com.androstock.smsapp.Chat$1.onClick(Chat.java:82)
        at android.view.View.performClick(View.java:5640)
        at android.view.View$PerformClick.run(View.java:22455)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6165)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

**Comment by mahdit83** [comment]
Hi @ravdeepsingh22 
Would you tell me where this happened and explain more about issue?  thanks
